node {

  // job
  try {
    stage("Deploy"){
        office365ConnectorSend webhookUrl: "https://o365adessogroup.webhook.office.com/webhookb2/06a9e3d3-196d-419b-be9a-5361c60217ba@3d355765-67d9-47cd-9c7a-bf31179f56eb/JenkinsCI/3489cc3d398c4037aefec8edc472d7e3/c7a7555f-358d-4baa-a245-56835ca83717",
        message: 'Code is deployed',
        status: 'Success'
    }
    stage('build') {
      println('so far so good...')
    }
    stage('test') {
      println('A test has failed!')
     // sh 'exit 1'
    }
  } catch(e) {
    // mark build as failed
    currentBuild.result = "FAILURE";

    // send slack notification
    slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")

    // throw the error
    throw e;
  }
}
